In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

In [181]:
logits = tf.random.uniform(minval=0, maxval=1, seed=42, shape=(5, 6))
logits

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0.70125747, 0.59246445, 0.6469835 , 0.78929853, 0.4893242 ,
        0.3564489 ],
       [0.87974083, 0.8299811 , 0.4734974 , 0.06678545, 0.37019384,
        0.8914565 ],
       [0.9230031 , 0.97236   , 0.9784479 , 0.99113977, 0.6481546 ,
        0.04302442],
       [0.26199007, 0.6073632 , 0.41687417, 0.33327353, 0.5742605 ,
        0.2488842 ],
       [0.8426975 , 0.03221571, 0.45767534, 0.19128656, 0.23360837,
        0.9743171 ]], dtype=float32)>

In [182]:
Q_marginal = tfd.MixtureSameFamily(
mixture_distribution=tfd.Categorical(logits=tf.zeros(tf.shape(logits)[0])),
    components_distribution=tfd.RelaxedBernoulli(logits=tf.transpose(logits),
                                                 temperature=1e-5)
)
Q_marginal

<tfp.distributions.MixtureSameFamily 'MixtureSameFamily' batch_shape=[6] event_shape=[] dtype=float32>

In [183]:
x = Q_marginal.sample(512)
x = tf.clip_by_value(x, 1e-7, 1.-1e-7)
tf.reduce_mean(-1. * tf.reduce_sum(Q_marginal.log_prob(x), axis=1))


<tf.Tensor: shape=(), dtype=float32, numpy=-18.08369>

In [186]:
tf.reduce_mean(-1. * Q_marginal.log_prob(x))

<tf.Tensor: shape=(), dtype=float32, numpy=-3.0139532>

In [154]:
tfd.RelaxedBernoulli(logits=logits[0], temperature=1e-5).sample(5)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1.69425517e-01, 2.86047843e-08, 9.99991059e-01, 1.26213822e-11,
        9.84694362e-01, 9.80800986e-01],
       [1.12091314e-07, 9.99999821e-01, 1.00000000e+00, 9.99950886e-01,
        9.99999762e-01, 9.99994159e-01],
       [9.99905467e-01, 1.00000000e+00, 9.99999762e-01, 1.87024474e-03,
        7.75832814e-06, 1.00000000e+00],
       [1.64315952e-06, 1.31407887e-06, 9.98902619e-01, 2.60528028e-02,
        1.00000000e+00, 9.99572515e-01],
       [8.47551376e-02, 7.52730131e-01, 2.94035551e-09, 9.84307036e-08,
        9.19312119e-01, 9.39749181e-01]], dtype=float32)>

In [46]:
tf.reshape(tf.repeat(tf.one_hot(tf.range(5), 5), 4, axis=0), shape=(5, 4, 5))

<tf.Tensor: shape=(5, 4, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.]],

       [[0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.]]], dtype=float32)>

In [40]:
logits = tf.random.uniform(shape=(4, 6))

In [39]:
tf.stack([logits] * 5)

<tf.Tensor: shape=(5, 4, 6), dtype=float32, numpy=
array([[[0.43997335, 0.7566391 , 0.72414565, 0.8721417 , 0.77916086,
         0.8345915 ],
        [0.8838308 , 0.9762491 , 0.9743644 , 0.60298705, 0.9274093 ,
         0.16422224],
        [0.16155815, 0.40403342, 0.6110437 , 0.7467438 , 0.37594604,
         0.8383919 ],
        [0.1807034 , 0.78149307, 0.10201752, 0.9994273 , 0.84367716,
         0.97526073]],

       [[0.43997335, 0.7566391 , 0.72414565, 0.8721417 , 0.77916086,
         0.8345915 ],
        [0.8838308 , 0.9762491 , 0.9743644 , 0.60298705, 0.9274093 ,
         0.16422224],
        [0.16155815, 0.40403342, 0.6110437 , 0.7467438 , 0.37594604,
         0.8383919 ],
        [0.1807034 , 0.78149307, 0.10201752, 0.9994273 , 0.84367716,
         0.97526073]],

       [[0.43997335, 0.7566391 , 0.72414565, 0.8721417 , 0.77916086,
         0.8345915 ],
        [0.8838308 , 0.9762491 , 0.9743644 , 0.60298705, 0.9274093 ,
         0.16422224],
        [0.16155815, 0.40403342, 0.

In [42]:
tf.stack([tf.one_hot(tf.range(5), 5)] * 5)

<tf.Tensor: shape=(5, 5, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)>

In [64]:
tf.reshape(tf.repeat(tf.expand_dims(tf.one_hot(2, 5), axis=0), 3, axis=0), shape=(3, 5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

In [60]:
tf.stack([tf.one_hot(2, 5)] * 3)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

In [4]:
latent_state_size = 3
batch_size = 6
action_size = 2

action = tf.random.uniform(
    shape=(batch_size, ), minval=0, maxval=action_size, dtype=tf.int32, seed=42)
action = tf.one_hot(action, action_size)

latent_states_logits = []
for _ in range(action_size):
    latent_states_logits.append(
        tf.random.uniform(shape=(batch_size, latent_state_size), seed=42))
# latent_states_stack = tf.stack(latent_states_logits, axis=1)

latent_states_stack = tf.random.uniform(shape=(batch_size, action_size, latent_state_size))
action_expand_dims = tf.expand_dims(action, -1)
action_tile = tf.tile(action_expand_dims, (1, 1, latent_state_size))
mult = action_tile * latent_states_stack
latent_states = tf.reduce_sum(mult, axis=1)

print("action", action)
print("latent_states_stack", latent_states_stack)
print("action_tile", action_tile)
print("mult", mult)
print(latent_states)

action tf.Tensor(
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]], shape=(6, 2), dtype=float32)
latent_states_stack tf.Tensor(
[[[0.29822934 0.83325636 0.142084  ]
  [0.81573653 0.8939357  0.21609187]]

 [[0.66496444 0.90702116 0.05573988]
  [0.4616239  0.8716624  0.21884048]]

 [[0.3344425  0.51248133 0.19966173]
  [0.7560613  0.01114261 0.44287622]]

 [[0.5316609  0.12373877 0.35417366]
  [0.6469995  0.06985843 0.6044067 ]]

 [[0.8172021  0.31625688 0.7307626 ]
  [0.3524387  0.87245095 0.68590915]]

 [[0.19558418 0.15751529 0.39862943]
  [0.20925236 0.28273594 0.54019547]]], shape=(6, 2, 3), dtype=float32)
action_tile tf.Tensor(
[[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [0. 0. 0.]]], shape=(6, 2, 3), dtype=float32)
mult tf.Tensor(
[[[0.29822934 0.83325636 0.142084  ]
  [0.         0.         0.        ]]

 [[0.66496444 0.90702116 0.05573988]
  [0.         0.        

In [27]:
print(tf.tile(action_expand_dims, (1, 1, latent_state_size)))
print(tf.reshape(tf.repeat(action_expand_dims, latent_state_size), shape=(batch_size, action_size, latent_state_size)))
print(tf.repeat(action_expand_dims, latent_state_size, axis=-1))

tf.Tensor(
[[[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]], shape=(6, 2, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]], shape=(6, 2, 3), dtype=float32)


<tf.Tensor: shape=(6, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [0., 0., 0.]]], dtype=float32)>

In [9]:
layers = []
# layers.append(tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, -1)))
layers.append(tf.keras.layers.RepeatVector(latent_state_size))
layers.append(tf.keras.layers.Permute(dims=(2, 1)))
sequential = tf.keras.Sequential(layers)
sequential(action)

<tf.Tensor: shape=(6, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [0., 0., 0.]]], dtype=float32)>

In [2]:
labels_logits = tf.random.uniform(shape=(8, 3))
latent_states_logits = tf.random.uniform(shape=(8, 7))
joint_distribution = tfd.JointDistributionSequential(
    [
        tfd.Independent(tfd.Bernoulli(logits=labels_logits, dtype=tf.float32)),
        lambda l: tfd.Independent(
            tfd.Logistic(loc=tf.concat([latent_states_logits, l], axis=-1) / 0.5,
                               scale=1. / 0.5))
    ], validate_args=True
)
samples = joint_distribution.sample()
samples

[<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
 array([[0., 0., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 1., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 0.],
        [1., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(8, 10), dtype=float32, numpy=
 array([[ 0.8750086 , -2.1764064 , -8.008769  ,  2.0827742 , -3.4839377 ,
         -1.9698689 ,  1.801935  , -5.7171316 ,  7.2105317 ,  0.07895708],
        [ 2.7532258 ,  9.3939705 ,  7.2280254 ,  0.37413168,  0.464877  ,
         -0.3894    ,  2.7742813 ,  2.417486  ,  4.5979443 , -0.46260595],
        [-3.586282  ,  6.6553297 ,  5.1713037 , -3.9721582 , 11.050644  ,
         -1.8404622 ,  7.3951654 ,  5.154852  , -0.06546402,  1.6761897 ],
        [-0.10868585,  0.06133366, -4.0239735 ,  3.019597  ,  6.071562  ,
         -0.7746917 ,  1.6853944 , -6.4726887 ,  2.144046  , -3.3958347 ],
        [ 1.9093564 , -1.1534448 ,  0.77691925, -0.739486  , -7.4870777 ,
         -0.10598338, -1.9725208 ,  1

In [44]:
next_label = tf.round(tf.random.uniform(shape=(8, 3), maxval=1, dtype=tf.float32))
next_latent_state = tf.random.uniform(shape=(8, 10))
next_label, next_latent_state

(<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [1., 0., 1.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 1.],
        [0., 1., 0.],
        [0., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(8, 10), dtype=float32, numpy=
 array([[0.5855373 , 0.14502394, 0.8167027 , 0.22830033, 0.5391594 ,
         0.5588813 , 0.348315  , 0.62111485, 0.562451  , 0.47691822],
        [0.4133531 , 0.288126  , 0.81695485, 0.63810074, 0.7901763 ,
         0.9822817 , 0.18364835, 0.4996612 , 0.3385446 , 0.83445966],
        [0.63412285, 0.74180174, 0.9497335 , 0.3783275 , 0.32327187,
         0.27079606, 0.65978396, 0.38685727, 0.48017752, 0.7811073 ],
        [0.36073804, 0.4966575 , 0.4298637 , 0.8285161 , 0.68470347,
         0.15770066, 0.41381884, 0.26814365, 0.77656853, 0.63847697],
        [0.12286198, 0.54415786, 0.771317  , 0.98686075, 0.19961941,
         0.6811857 , 0.62611806, 0.12596726, 0.380929  , 0.4824555 ],
        [0.4

In [45]:
joint_distribution.log_prob(samples)

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-26.934498, -29.217688, -27.872187, -28.394295, -28.530806,
       -30.18421 , -27.706776, -28.420433], dtype=float32)>

In [46]:
joint_distribution.log_prob_parts(samples)

[<tf.Tensor: shape=(8,), dtype=float32, numpy=
 array([-2.0427217, -1.8208035, -2.3500047, -2.1035583, -2.1162028,
        -2.218251 , -1.6465869, -1.7633481], dtype=float32)>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=
 array([-24.891775, -27.396885, -25.522182, -26.290737, -26.414602,
        -27.96596 , -26.060188, -26.657085], dtype=float32)>]

In [49]:
tfd.Independent(tfd.Bernoulli(logits=labels_logits, dtype=tf.float32)).kl_divergence(
    tfd.Independent(tfd.Bernoulli(logits=labels_logits/3., dtype=tf.float32)),
)

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([0.04330206, 0.09924033, 0.01345113, 0.05217344, 0.02215266,
       0.02880204, 0.06082198, 0.05492666], dtype=float32)>

In [4]:
d = tfd.Independent(tfd.Bernoulli(logits=labels_logits, dtype=tf.float32))
d.log_prob(samples[0])

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-2.5189648, -1.6360064, -1.1548808, -1.9831101, -2.8774555,
       -1.0599548, -1.8747082, -1.9544212], dtype=float32)>

In [10]:
latent_states_logits = tf.random.uniform(shape=(2, 5))
print(latent_states_logits)
tf.tile(tf.expand_dims(latent_states_logits, axis=0), [2, 1, 1])

tf.Tensor(
[[0.6016984  0.00395894 0.6886418  0.53072643 0.24391103]
 [0.26492536 0.00718594 0.84086215 0.92504025 0.25911975]], shape=(2, 5), dtype=float32)


<tf.Tensor: shape=(2, 2, 5), dtype=float32, numpy=
array([[[0.6016984 , 0.00395894, 0.6886418 , 0.53072643, 0.24391103],
        [0.26492536, 0.00718594, 0.84086215, 0.92504025, 0.25911975]],

       [[0.6016984 , 0.00395894, 0.6886418 , 0.53072643, 0.24391103],
        [0.26492536, 0.00718594, 0.84086215, 0.92504025, 0.25911975]]],
      dtype=float32)>

In [3]:
logits = tf.random.uniform(shape=(8, 5, 2))
print(logits)
print(tf.transpose(logits, perm=[0, 2, 1]))

tf.Tensor(
[[[0.6006433  0.67991614]
  [0.81787026 0.12673628]
  [0.55159366 0.44886363]
  [0.11846972 0.9160278 ]
  [0.6887318  0.8214159 ]]

 [[0.8509476  0.6643053 ]
  [0.04173446 0.13981605]
  [0.57558167 0.86658955]
  [0.55009484 0.01074302]
  [0.77765155 0.9054495 ]]

 [[0.7815635  0.5418669 ]
  [0.3591491  0.93506575]
  [0.56423914 0.41349697]
  [0.8498039  0.04684567]
  [0.7024456  0.3418888 ]]

 [[0.9156854  0.51061976]
  [0.24824917 0.39826155]
  [0.91608083 0.09705913]
  [0.6768075  0.03017676]
  [0.1852957  0.21276796]]

 [[0.06404328 0.15965962]
  [0.92984366 0.62456286]
  [0.76914537 0.7628404 ]
  [0.45913315 0.308496  ]
  [0.5244534  0.80049515]]

 [[0.78989947 0.29715443]
  [0.06213367 0.3046744 ]
  [0.9191748  0.46890056]
  [0.1735295  0.8635168 ]
  [0.36209726 0.36810887]]

 [[0.47330177 0.6807072 ]
  [0.2522719  0.02376568]
  [0.8912535  0.28865123]
  [0.15856159 0.46589887]
  [0.7337228  0.39314902]]

 [[0.3093865  0.44615376]
  [0.85369444 0.35040128]
  [0.9418485 

In [7]:
tfd.Independent(tfd.Bernoulli(logits=tf.transpose(logits, perm=[0, 2, 1])), reinterpreted_batch_ndims=1)

<tfp.distributions.Independent 'IndependentBernoulli' batch_shape=[8, 2] event_shape=[5] dtype=int32>